### ISSUE TITLE
QGIS Plugin

### ISSUE THREAD

**Issue by NyakudyaA** [PrakritiShetty/GNR633Project_QGISPlugin#1]
Maybe you could have the plugin published https://plugins.qgis.org/, it will gain a larger audience that the developer email. If you feel the plugin is not mature enough then flag it as experimental.

While you are at it please also remove https://github.com/PrakritiShetty/GNR633Project_QGISPlugin/tree/main/fis_plugin/__pycache__, it's autogenerated on install

**Comment by prakritishetty** [comment]
Resolved
